# Generated by Django 2.2.4 on 2019-08-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('text', models.TextField(null=True)),
                ('monetary_sanction', models.FloatField(null=True)),
                ('type', models.TextField(null=True)),
                ('decision_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
