# Generated by Django 2.2.4 on 2019-08-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('jurisdiction', models.TextField(null=True)),
                ('type', models.TextField(null=True)),
                ('publication_website', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
            ],
        ),
    ]
