# Generated by Django 2.2.4 on 2019-08-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='violations',
            field=models.ManyToManyField(to='api.Violation'),
        ),
    ]
