# Generated by Django 2.2.4 on 2019-08-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_decision_violations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='violations',
            field=models.ManyToManyField(blank=True, null=True, to='api.Violation'),
        ),
    ]
