# Generated by Django 2.2.4 on 2019-08-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190829_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decision',
            name='authority',
        ),
    ]
