# Generated by Django 2.2.4 on 2019-08-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_decision_authority'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='authorities',
            field=models.ManyToManyField(blank=True, null=True, to='api.Authority'),
        ),
    ]
