# Generated by Django 2.2.4 on 2019-09-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190906_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='justice_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
