# Generated by Django 2.2.4 on 2019-09-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190913_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='api.Organization'),
        ),
    ]
