# Generated by Django 2.2.4 on 2019-09-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_decision_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='authorities',
            field=models.ManyToManyField(blank=True, related_name='decisions', to='api.Authority'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='decisions', to='api.Organization'),
        ),
        migrations.AlterField(
            model_name='decision',
            name='violations',
            field=models.ManyToManyField(blank=True, related_name='decisions', to='api.Violation'),
        ),
    ]
