- name: Install nvm
  become: yes
  become_method: sudo
  become_user: "{{ install_user }}"
  shell: >
    curl -o- {{ nvm_url }} | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    warn: no
  tags:
    - nodejs

- name: Install nodejs
  shell: "source {{ home_dir }}/.nvm/nvm.sh && nvm install {{ nodejs_version }} && nvm alias default {{ nodejs_version }}"
  args:
    executable: /bin/bash
  tags:
    - nodejs